export const ACTION_TYPES = {
  LOGIN_REQUEST: 'auth.LOGIN_REQUEST',
  LOGIN_SUCCESS: 'auth.LOGIN_SUCCESS',
  LOGIN_FAILED: 'auth.LOGIN_FAILED',
  SIGN_UP_REQUEST: 'auth.SIGN_UP_REQUEST',
  SIGN_UP_FAILED: 'auth.SIGN_UP_FAILED',
  CHANGE_PASSWORD_REQUEST: 'auth.CHANGE_PASSWORD_REQUEST',
  SIGN_OUT: 'auth.SIGN_OUT',
  SET_TOKEN: 'auth.SET_TOKEN',
};
