export const ACTION_TYPES = {
  LOGIN_REQUEST: 'auth.LOGIN_REQUEST',
  LOGIN_SUCCESS: 'auth.LOGIN_SUCCESS',
  SIGN_IN_REQUEST: 'auth.SIGN_IN_REQUEST',
  CHANGE_PASSWORD_REQUEST: 'auth.CHANGE_PASSWORD_REQUEST',
  SIGN_OUT: 'auth.SIGN_OUT',
};
